version: '2.0'

services:
  web:
    build: .
    command: gunicorn app:app --bind 0.0.0.0:$PORT
    environment:
      PORT: 80
    ports:
      - "80:80"
    volumes:
      - .:/todo
    depends_on:
      - db